apiVersion: kustomize.config.k8s.io/v1beta1
metadata:
  name: demo-app
kind: Kustomization
namespace: demo
resources:
  - namespace.yaml
  - release.yaml
  - service.yaml

configMapGenerator:
  - name: demo-app-cm
    files:
      - application.properties
