apiVersion: kustomize.config.k8s.io/v1beta1
metadata:
  name: infra-controllers-resources
kind: Kustomization
resources:
  - cert-manager.yaml
  - ingress-nginx.yaml
  - kube-prometheus-stack.yaml
  - external-dns.yml
